# Site settings
title: "Flutter中文文档"
email: me67554@gmail.com
email_name: me67554
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://doc.flutterdart.cn"
cdn: "https://file.flutterdart.cn/website"
github_username: flutter
description: Flutter中文网是中国最大的Flutter开发者交流学习平台，致力于打造Flutter开发中文社区。在这里能轻松找到代码实例、项目案例、并有专人提供最新文档翻译。
keywords: flutter中文网, flutter教程, Flutter中文网, flutter文档

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

exclude: [example, packages, tool]
