# Site settings
title: "Flutter中文文档"
email: me67554@gmail.com
email_name: flutter-dev@
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://doc.flutterdart.cn"
cdn: "https://file.flutterdart.cn/website"
github_username: flutter
description: Flutter中文文档基于google官方flutter英文文档翻译，由专人提供最新文档翻译，是世界最好的flutter中文文档。
keywords: flutter中文, flutter中文文档, flutter中文教程

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

exclude: [example, packages, tool]
